# Generated by Django 3.0 on 2019-12-17 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Enter login!', max_length=25)),
                ('email', models.EmailField(help_text='Enter email!', max_length=100)),
                ('password', models.CharField(help_text='Enter password!', max_length=25)),
                ('date_create', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='table_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_link', models.URLField(help_text='Enter full link!', max_length=500)),
                ('short_link', models.URLField(help_text='Enter Short link!')),
                ('number_of_clicks', models.IntegerField(default=0, help_text='Number of clicks on the link')),
                ('id_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='antidas.Registration')),
            ],
        ),
    ]
