# Generated by Django 3.0 on 2019-12-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antidas', '0002_auto_20191217_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(help_text='Enter email!', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='login',
            field=models.CharField(help_text='Enter login!', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(help_text='Enter password!', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='table_link',
            name='id_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='antidas.Registration'),
        ),
        migrations.AlterField(
            model_name='table_link',
            name='short_link',
            field=models.URLField(help_text='Enter Short link!', unique=True),
        ),
    ]
