# Generated by Django 3.0 on 2019-12-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antidas', '0002_auto_20191217_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_link',
            name='id_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='antidas.Registration'),
        ),
        migrations.AlterField(
            model_name='table_link',
            name='short_link',
            field=models.URLField(help_text='Enter Short link!'),
        ),
    ]
