# Generated by Django 3.0.1 on 2019-12-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antidas', '0012_auto_20191223_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_link',
            name='user_login',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
